### PR TITLE
make beastmaster buy agh scepter as first item & fix turbo shard timing

### PR DESCRIPTION
**Pull request by christiandwi**
- make beastmaster buy agh scepter as first item
- fix turbo shard timing, it's actually 7:30 but for the sake of code simplicity, i used 8 minutes

### CODE REVIEW

**Comment by forest0xia** [comment]
Why agh scepter first?

**Comment by forest0xia** [comment]
looking at the guides, https://www.dotabuff.com/heroes/brewmaster/guides, i dont see anyone suggest buying agh as the first item. And this kind of build wasn't good for farming or fights as bots. if you want to improve brewmaster, please try to make it able to use abilities better, and most importantly, improve the way it uses the ult. Right now the summoned element units are not able to use abilities in a proper way like blowing an enemy when the team is able to kill the enemy and this often time interrupts allies to kill enemies.

**Comment by christiandwi** [comment]
Sorry, i think you saw the hero name wrong. It's for beastmaster not brewmaster. Beastmaster's scepter is a first item build in pro scene. It heals, damages, and makes beastmaster stronger against illusion / gank

**Comment by forest0xia** [comment]
Haha oh no! I made this mistake every time I looked at their names.

**Comment by christiandwi** [comment]
Hahaha it happens to all of us, let me try fixing the brewmaster one

**Pull request merged**
