### PR TITLE
Draft: TS integration

### PR DESCRIPTION
**Pull request by ThirVondukr**
I have no idea what I'm doing regarding IO script itself, please give any feedback regarding bot script itself or TS integration 🤔.  
P.S. For some reason IO generally behaves very badly, diving heroes, etc, I assume it's not caused by my changes?

### CODE REVIEW

**Comment by forest0xia** [comment]
Hey ThirVondukr, first of all thanks a lot for brining in the typescript-to-lua dependency and set this up. I think this is a great start.
Also, thanks for raising this to check with me first before adding a lot of things to it.

It can be a lot better if we can put the source code in different paths like below, and set the generated path of the lua files to the relative bots folder, such that we can keep the code base clean for better maintenance and less confusion. for example:
```
root
│   README.md
│   .gitignore
│   [other config files]
└───bots (lua scripts)
│   │
│   └───BotLib
│       │   hero_wisp.lua
│   ...
└───typescript (ts scripts)
│   │
│   └───interfaces (all interfaces)
│       │   bots_general.d.ts
│       │   ...
│       └───valve_scripting (interfaces from Valve https://developer.valvesoftware.com/wiki/Dota_Bot_Scripting)
│           │   globals.d.ts
│           │   unit.d.ts
│           │   ability.d.ts
│           │   ...
│           
│   └───bot_lib (all bot logic in ts)
│       │   hero_wisp.ts
│       │   ...
│ 
│   └───lib
│       │   [other ts utilities]
│ 
```

**Comment by forest0xia** [comment]
> For some reason IO generally behaves very badly

This is because IO is buggy due to missing default bot logic from Valve. This is not because of your change, it's a bug on Valve side - those buggy heroes like IO will only simply go to a dummy target point and don't do anything that makes sense unless we override the relative behavior.

I fixed those buggy heroes by implementing a simple override layer for laning and attack logic. This is also to be improved.

I wonder how you wrote the ts code for IO. Did you write it on your own, or used some tools for help? I like the idea of 
```
const roleItemBuyList: { [key in BotRole]: string[] } = {
    pos_1: defaultBuild,
...
```
I think since we are doing this refactoring, a more complex mapping may make more sense:
```
{
pos_1 -> item-build, ability-build, talent-build, etc, 
pos_2 -> item-build, ability-build, talent-build, etc, 
}
```

A general feedback on new util-like methods such as:
```
function HasHealingEffect(hero: Unit) {
    const modifiers = [
```
please first check if there's such method in `bots/FunLib/jmz_func.lua`, or `bots/FunLib/utils.lua`, if not then add it to a generic utils file since it can be shared across different files.

Please add a brief intro to the ts files you add, so we can share the context what to expect from those files to avoid mis-use or mis-add/mix of functionality.

And you dont need to keep the `bots/BotLib/hero_wisp.reference.lua` file for reference. we can always ref the historical commits.

**Comment by ThirVondukr** [comment]
I just rewrote the IO code to be more type safe 🙂
Regarding using different paths - maybe it would be better to do that after all the code is migrated to TS?

For builds it would be better to use an interface/object:
```lua
interface BotBuild {
  items: {
    buy: string[]
    sell: string[]
  }
  ...
}

{
pos_1 -> {...}, 
pos_2 -> {...}, 
}
```

Also it would be great to talk with you outside of github to collaborate easier.

**Comment by forest0xia** [comment]
> For builds it would be better to use an interface/object

good point, yeah we can do that too. I have not been using ts for a long time, hopefully this big nested entity won't be too hard to use.

> Regarding using different paths - maybe it would be better to do that after all the code is migrated to TS?

We should do it in the beginning, because we know it's anyway should be achieved for the long run and I dont want any conflicts or accidental changes to the ts files when we and potentially other people later working together on this project. Maybe something like following:

```
// in tsconfig.json: 
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "CommonJS",
    "strict": true,
    "outDir": "tempBuild",  // Temporary directory for all compiled Lua files
    "rootDir": ".",       // Base directory for TypeScript source files
  },
```

```
// Add a build.js file:
const fs = require('fs');
const path = require('path');

const folders = [
  { src: 'tempBuild/bot_lib', dest: 'bots/BotLib' },
  { src: 'tempBuild/fun_lib', dest: 'bots/FunLib' },
];

folders.forEach(({ src, dest }) => {
  fs.mkdirSync(dest, { recursive: true });
  fs.readdirSync(src).forEach(file => {
    const srcPath = path.join(src, file);
    const destPath = path.join(dest, file);
    fs.renameSync(srcPath, destPath);
  });
});

// Optionally, clean up the tempBuild directory
fs.rmSync('tempBuild', { recursive: true, force: true });

```

```
// package.json:
{
  "scripts": {
    "build": "tstl && node build.js"
  }
}

```

**Comment by forest0xia** [comment]
can add me in discord: forest0xia

**Comment by forest0xia** [comment]
In case you or anyone else wants to know more about the bugged heroes or bugs from Valve side for bots support, check this post, I had shared part of the bugs in reddit: https://www.reddit.com/r/DotA2/comments/1ezxpav/a_note_to_valve_official_regarding_bot_scripts/

**Comment by forest0xia** [comment]
Bro, following up on this. We likely will have more conflicts as we both keep modifying same files for our updates. What is your plan to fix conflicts and merge a initial verison?

**Comment by ThirVondukr** [comment]
Hey, sorry, but I was a bit busy recently, we don't have to migrate whole project in one go, we can solve current conflicts and merge the changes, we could use generated lua in existing lua files that we didn't yet migrate.

**Comment by forest0xia** [comment]
#No worries man. Take care and take your time. I'm also busy recently lol and just had an orthopedic surgery. 

To clarify my point for the previous comment was: to minimize the conflicts that can cause unexpected behaviors. Please keep your changes as minimal as possible for the initial integration with TS. 
Obviously we are aligned on this already, but I'd like to make it clear so you are not adding more or converting more files while trying to wrap up your work for the commit.

**Comment by ThirVondukr** [comment]
I think I can solve the conflicts with `utils`, `version` and `hero_wisp` files and let you know

**Comment by ThirVondukr** [comment]
@forest0xia I've solved a couple of conflicts in utils and wisp script, can we merge the changes or is there something you'd like to change?

**Comment by ThirVondukr** [comment]
Decided to just provide optional defaults for enum values in case these globals are nil
https://github.com/ThirVondukr/dota2bot-OpenHyperAI/blob/a6cd1577799b6ae229bd35dff62d59cc5c9c1452/bots/lib/dota/enums.ts#L71

**Comment by forest0xia** [comment]
Impressive work @ThirVondukr ! Thanks for making this change <3

**Comment by forest0xia** [comment]
Apparently there were some errors in utils.ts and other place in the merged commit. I just fixed them. I also refactored the file structure, and moved jmz_func to typescript folder for now. Let's start from the current state to use ts.

Btw, BotBehavior needs further refactoring. We need to break it down. It's not adding value but simply making unnecesary structure for now.  It will be harder to manage and harder to review later for bots that has very large BotBehavior. Take a look at Invoker lua.
Also, as we've discussed, we want to optimize code structure for different positions. for example pos1 should have a specific item-build, ability-build, talent-build etc. so pos1 wisp should get a pos1 build for all things (e.g. item-build[1], ability-build[1], talent-build[1]), and pos2 wisp should get a pos2 build for all things. Let's add this later as well.

**Comment by forest0xia** [comment]
@ThirVondukr ^^

**Pull request merged**
