### PR TITLE
feat: add HeroName enum

### PR DESCRIPTION
**Pull request by ThirVondukr**

### CODE REVIEW

**Comment by forest0xia** [comment]
Lone bear is also a hero unit. Search the code in lua for its full name

**Comment by forest0xia** [comment]
Think the Ringmaser is also not yet included.

**Comment by forest0xia** [comment]
Valve official site has been out dated for so long. lmao.

**Comment by ThirVondukr** [comment]
> Lone bear is also a hero unit. Search the code in lua for its full name

I thought we'd use this enum in matchups for example, lone bear isn't a hero you can pick 😅

**Comment by forest0xia** [comment]
We'd use this whenever we see convenient later since we call it as generic as HeroName not HeroNameForMatchup. This is always how legacy code in projects grow like.
So if not now, we will need to add it soon if we want to get the most of this enums as we migrate more features to ts

**Comment by forest0xia** [comment]
On a second thought, it's probably better to put bear name in some kind of UnitName enum since most people won't think it's a hero by default.

**Pull request merged**
