### PR TITLE
Remove quelling blade from sell list

### PR DESCRIPTION
**Pull request by angpoginiko**
Makes PA not able to buy BF.

match code for reference:
7978520552

### CODE REVIEW

**Comment by forest0xia** [comment]
1. This isn't the root cause. Why would pa buy a bkb before buying a bf?

2. This fix will cause issues. You need to pair the items for selling. Items the selling list is paired with another item: when gets the first item -> sells the second item

**Comment by forest0xia** [comment]
Let me know if the above comment makes sense to you. I think without this code fix the PA should still be able to compete the BF. You can try to play a few more games and pick a PA for bots. 

I'm going to close this issue in a few days since this won't fix any issue but can cause more issues.

**Comment by angpoginiko** [comment]
I just did this as a workaround, whenever they sell the quelling they wont be able to complete the BF. I'm not sure whats the correct fix.

**Comment by forest0xia** [comment]
> This workaround worked too, because I tried having PA in my next game and it was able to buy BF normally.

my point is bots can complete BF even without your fix. we need to know what is the actual root casue first before being able to fix it. And it seems we both dont know what the actual issue is here

**Comment by forest0xia** [comment]
it was because of 
```
"item_power_treads",
"item_quelling_blade",
```
such that PA sells qb onces she gets pt
I've fixed it in commit: https://github.com/forest0xia/dota2bot-OpenHyperAI/commit/e5a7891c5a1db49d416a366026cd3f4446eecc35

**Comment by forest0xia** [comment]
Thanks for reposting this issue

**Comment by forest0xia** [comment]
a reminder, don't change the code the way you did, even if you saw some issues got fixed, you introduced issues such that other heroes may not be able to sell items properly and potentially other issues .

**Comment by forest0xia** [comment]
But dont get me wrong. I like to see more changes from you, just not the same buggy code without understanding the larger picture. Hope what I said can be heard

**Comment by angpoginiko** [comment]
Oh no problem. Was just experimenting base on what I understand on the code. Thanks for fixing it,

**Pull request closed without merging**
